version: '3.8'

services:

  app:
    build: .
    ports:
      - "3000:3000" 
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/mydatabase 
    networks:
      - app-network

  
  mongodb:
    image: mongo:latest
    volumes:
      - mongodb-data:/data/db  
    ports:
      - "27017:27017"  
    networks:
      - app-network

volumes:
  mongodb-data:

networks:
  app-network:
    driver: bridge
